
build:
  version: "3.0"

loans:
  message: "Welcome to the Bank loans related local APIs "
  contactDetails:
    name: "Greg - Developer"
    email: "greg@bank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934