
build:
  version: "1.0"

cards:
  message: "Welcome to the Bank cards related prod APIs "
  contactDetails:
    name: "Sandra - Product Owner"
    email: "sandra@bank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721