
build:
  version: "1.0"

loans:
  message: "Welcome to the Bank loans related prod APIs "
  contactDetails:
    name: "Ken - Product Owner"
    email: "ken@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956